name: Build and Test

on:
  push:
    branches:
      - main
      - feature/*

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'
          cache: 'true'

      - name: Run go vet
        run: go vet ./...

      - name: Build the application
        run: go build -v ./...

      - name: Run tests
        run: go test ./...
